version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: typedoc
    versions:
    - 0.20.25
    - 0.20.27
    - 0.20.30
    - 0.20.34
  - dependency-name: "@relaycorp/relaynet-core"
    versions:
    - 1.42.9
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: "@relaycorp/shared-config"
    versions:
    - 1.4.11
